name: angular_tour_of_heroes
description: Tour of Heroes
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev.3.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha+4
  angular_forms: ^1.0.1-alpha+2
  angular_router: ^2.0.0-alpha+2
  http: ^0.11.0
  stream_transform: ^0.0.6

dev_dependencies:
  angular_test: ^2.0.0-alpha
  build_runner: ^0.7.8
  build_test: ^0.10.0
  build_web_compilers: ^0.2.1
  mockito: ^2.0.2
  test: ^0.12.30

dependency_overrides:
  analyzer: ^0.31.0-alpha.1
